export const UI_TEXT = {
  // Buttons
  cancel: "取消",
  save: "保存",
  search: "搜索",
  previous: "上一页",
  next: "下一页",
  create: "创建",
  delete: "删除",
  edit: "编辑",
  refresh: "刷新",
  send: "发送",
  stop: "停止",
  pull: "拉取",
  test: "测试",
  upload: "上传",
  download: "下载",
  close: "关闭",
  start: "启动",
  pause: "暂停",
  resume: "恢复",
  back: "返回",
  add: "添加",

  // Status
  live: "在线",
  connecting: "连接中",
  disconnected: "已断开",
  idle: "空闲",
  running: "运行中",
  paused: "已暂停",
  created: "已创建",
  stopped: "已停止",
  failed: "失败",
  done: "完成",
  pending: "等待中...",
  enabled: "已启用",
  disabled: "已禁用",

  // Column headers
  user: "用户",
  role: "角色",
  host: "主机",
  account: "账号",
  password: "密码",
  port: "端口",
  type: "类型",
  status: "状态",
  updated: "更新时间",
  createdDate: "创建时间",
  actions: "操作",
  image: "镜像",
  owner: "所有者",
  proxy: "代理",
  container: "容器",
  name: "名称",
  size: "大小",
  modified: "修改时间",
  permissions: "权限",

  // Metrics
  total: "总计",
  admins: "管理员",
  users: "用户",
  ssh: "SSH",
  dockerPorts: "Docker端口",
  working: "进行中",
  projectSessions: "项目会话",
  assets: "资产",
  findings: "发现",
  relationships: "关系",
  sessions: "会话",
  tor: "Tor",
  poolSize: "池大小",
  mainTurns: "主轮次",
  compression: "压缩",

  // Empty states
  noUsersFound: "未找到用户",
  noHostsFound: "未找到主机",
  noProxiesFound: "未找到出口代理",
  noImagesFound: "未找到镜像",
  noContainersFound: "未找到容器",
  noProjectsFound: "未找到项目",
  noAssets: "暂无资产",
  noTasks: "暂无任务",
  noSummaries: "暂无摘要",
  noData: "暂无数据",
  emptyDirectory: "此目录为空",
  loading: "加载中...",

  // Pager
  pageOf: (page: number, start: number, end: number, total: number) =>
    `第 ${page} 页 · ${start}-${end} / 共 ${total} 条`,

  // Confirmations
  deleteConfirm: (name: string) => `删除 ${name}?`,

  // Auth
  signIn: "登录",
  email: "邮箱",
  passwordPlaceholder: "输入密码",
  leaveBlankToKeep: "留空保持当前密码不变",

  // Brand
  brand: "破晓 Daybreak",
  brandSubtitle: "安全评估平台",
  console: "破晓 控制台",

  // Navigation
  navPlayground: "工作台",
  navPlaygroundEyebrow: "智能工作台",
  navWorkProjects: "项目运营",
  navWorkProjectsEyebrow: "项目运营",
  navHosts: "主机管理",
  navHostsEyebrow: "基础设施接入",
  navEgressProxies: "出口代理",
  navEgressProxiesEyebrow: "网络出口",
  navSandboxImages: "沙箱镜像",
  navSandboxImagesEyebrow: "执行基线",
  navSandboxContainers: "沙箱容器",
  navSandboxContainersEyebrow: "运行实例",
  navSystemUsers: "系统用户",
  navSystemUsersEyebrow: "访问控制",
  navSystemConfig: "系统配置",
  navSystemConfigEyebrow: "运行时配置",

  // Playground
  newChat: "新对话",
  selectSandbox: "选择沙箱",
  noSandbox: "无沙箱",
  sendPlaceholder: "发送消息 · Shift+Enter 换行",
  streamingPlaceholder: "正在接收回复… 按 Enter 或停止以中断",
  loadingHistory: "正在加载对话历史…",
  finishSubagentFirst: "请先完成或取消正在运行的子代理任务",
  selectSandboxFirst: "请先选择一个沙箱",
  sandboxNotRunning: "所选沙箱未运行",
  noPermission: "无权操作此沙箱",
  noSubagentMessages: "暂无子代理消息",
  projectSession: "项目会话",
  untitledSession: "未命名会话",
  noConversations: "暂无对话",
  loadingSessions: "加载会话中...",
  noAgents: "暂无可用智能体",
  pickAgent: "选择智能体",
  agent: "智能体",

  // File manager
  uploadFiles: "上传文件",
  downloadSelected: "下载所选",
  copySelected: "复制所选",
  cutSelected: "剪切所选",
  pasteItems: (count: number) => `粘贴 ${count} 个项目`,
  nothingToPaste: "无内容可粘贴",
  deleteSelected: "删除选中项",
  deleteSelectedConfirm: (count: number) => `删除 ${count} 个选中项?`,
  itemsCopied: (count: number) => `${count} 项已复制到剪贴板`,
  itemsCut: (count: number) => `${count} 项已剪切到剪贴板`,
  itemsMoved: (count: number) => `${count} 项已移动`,
  itemsDeleted: (count: number) => `${count} 项已删除`,
  directoryCreated: "目录已创建",
  fileCreated: "文件已创建",
  filesUploaded: (count: number) => `${count} 个文件已上传`,
  fileSaved: "文件已保存",
  newFolder: "新建文件夹",
  newFile: "新建文件",
  listView: "列表视图",
  iconView: "图标视图",
  cut: "剪切",
  copied: "已复制",
  clear: "清除",

  // File viewer
  textFile: "文本",
  imageFile: "图片",
  binaryFile: "二进制",
  bytes: "字节",
  lines: "行",
  binaryCannotPreview: "二进制文件无法预览",
  failedToRead: "读取文件失败",
  failedToRender: "渲染图片失败",
  loadingViewer: "加载查看器...",
  loadingEditor: "加载编辑器...",
  loadingPreview: "加载预览...",

  // Network error
  networkError: "网络请求失败",

  // Egress
  egressMode: "出口模式",
  direct: "直连",
  managedProxy: "托管代理",
  selectEgressProxy: "选择出口代理",
  noEgressProxies: "无出口代理",
  testProxy: "测试代理",

  // TLS
  plain: "明文",
  tls: "TLS",

  // Sandbox
  createSandboxContainer: "创建沙箱容器",
  controlPort: "控制端口",
  capabilities: "能力",
  none: "无",
  pendingCreate: "等待创建",
  containerId: "容器ID:",
  portMappings: "端口映射",
  noExposedPorts: "无暴露端口",
  to: "至",
  tcp: "TCP",
  udp: "UDP",

  // Work project
  ownerLabel: "所有者",
  sandboxLabel: "沙箱",
  taskProgress: "任务进度",
  tasks: "任务",
  agentSummaries: "智能体摘要",
  attackPaths: "攻击路径",
  graph: "关系图",
  noAttackPaths: "暂无攻击路径",
  noAssetsToGraph: "无资产可绘制关系图",
  noDescription: "无描述",
  backToProjects: "返回",
  invalidProject: "无效项目",

  // Config
  runtime: "运行时",
  agentPool: "智能体池",
  agents: "智能体",
  newAgent: "新智能体",
  description: "描述",
  contextWindow: "上下文窗口",
  useResponsesApi: "使用 Responses API",
  baseUrl: "基础 URL",
  model: "模型",
  apiKey: "API 密钥",
  mainMaxTurns: "主最大轮次",
  subordinateMaxTurns: "子代理最大轮次",
  streamIdleTimeout: "流式空闲超时",
  contextCompression: "上下文压缩",
  triggerRatio: "触发比率",
  hardStopRatio: "硬停止比率",
  targetRatio: "目标比率",
  modelCallBudget: "模型调用预算",
  preserveRecentRatio: "保留近期比率",
  preserveRecentItems: "保留近期项数",
  minimumItems: "最小项数",
  summaryMaxTokens: "摘要最大 Token 数",
  maxSize: "最大大小",
  ttlSeconds: "TTL 秒数",
  sweepIntervalSeconds: "清理间隔秒数",
  selectManagedHost: "选择受管主机",
  selectSandboxImage: "选择沙箱镜像",
  selectContainerOwner: "选择容器所有者",
  noHosts: "无主机",
  noImages: "无镜像",
  noUsers: "无用户",
  noRunningContainers: "无运行中容器",
  noEmail: "无邮箱",
  loadingHosts: "加载主机中...",
  loadingImages: "加载镜像中...",
  loadingUsers: "加载用户中...",
  loadingContainers: "加载容器中...",
  pendingHash: "等待哈希",
  unsupported: "不支持",
  supported: "支持",
  imagePlaceholder: "ghcr.io/org/image:latest",
  searchIpAccount: "搜索 IP、账号、SSH 端口或 Docker 端口",
  searchUsername: "搜索用户名或邮箱",
  searchImageName: "搜索镜像名称",
  searchProjectName: "搜索项目名称、类型、描述或状态",
  searchContainer: "搜索容器、镜像、所有者、端口或状态",
  searchHostAccount: "搜索主机、账号、类型或端口",
  loadingSandboxes: "加载沙箱中",
  createHost: "创建主机",
  createProxy: "创建出口代理",
  createImage: "创建镜像",
  createContainer: "创建容器",
  createUser: "创建用户",
  createProject: "创建项目",
  refreshUsers: "刷新用户",
  refreshHosts: "刷新主机",
  refreshProxies: "刷新出口代理",
  refreshImages: "刷新沙箱镜像",
  refreshContainers: "刷新沙箱容器",
  refreshProjects: "刷新项目",
  refreshConfig: "刷新配置",
  editHost: "编辑主机",
  editProxy: "编辑出口代理",
  editProject: "编辑项目",
  editUser: "编辑用户",
  ipAddress: "IP 地址",
  sshPort: "SSH 端口",
  hostAccount: "主机账号",
  hostPassword: "主机密码",
  dockerPort: "Docker 管理端口",
  dockerTlsMode: "Docker TLS 模式",
  dockerCaCert: "Docker 客户端 CA 证书",
  dockerClientCert: "Docker 客户端证书",
  dockerClientKey: "Docker 客户端密钥",
  proxyType: "代理类型",
  proxyHost: "代理主机",
  proxyPort: "代理端口",
  proxyAccount: "代理账号",
  proxyPassword: "代理密码",
  portMapping: "端口映射",
  removePortMapping: "移除端口映射",
  username: "用户名",
  projectName: "项目名称",
  projectType: "项目类型",
  projectOwners: "项目所有者",
  sandboxContainer: "沙箱容器",
  projectDescription: "项目描述",
  projectAssets: "项目资产",
  addAsset: "添加资产",
  assetType: "类型",
  assetPath: "路径",
  assetHost: "主机",
  assetDomain: "域名",
  assetNetwork: "网络 (CIDR)",
  assetPort: "端口",
  removeAsset: "移除资产",
  hide: "隐藏",
  show: "显示",
  hideSecret: "隐藏密钥",
  showSecret: "显示密钥",
  secretFor: (name: string) => `${name} 的密钥`,
  imagesOnHost: (ip: string) => `${ip} 上的镜像`,
  hostImages: "主机镜像",
  selectImagesToPull: "选择要拉取的镜像",
  removeImage: "移除镜像",
  removeImageConfirm: (name: string) => `移除 ${name}?`,
  hash: "哈希",
  deleteContainer: "删除容器",
  deleteHostTitle: "删除主机",
  deleteProxyTitle: "删除出口代理",
  deleteImageTitle: "删除镜像",
  deleteUserTitle: "删除用户",
  deleteProjectTitle: "删除项目",
  deleteProjectConfirm: (name: string) => `删除 ${name} 及所有项目会话?`,
  deleteSession: "删除会话",
  deleteChat: "删除对话",
  deleteChatConfirm: "永久删除此对话?",
  deleteSessionConfirm: "永久删除此项目会话?",
  editSessionTitle: "编辑会话标题",
  deleteSelectedItems: "删除选中项",
  createSandboxImage: "创建沙箱镜像",
  sandboxImageName: "镜像名称",
  controlPortLabel: "控制端口",
  torLabel: "Tor",
  egressModeLabel: "出口模式",
  managedProxyLabel: "托管代理",
  workProject: "工作项目",
  noProjectSelected: "未选择项目",
  newProjectSession: "新项目会话",
  removePortMappingLabel: "移除端口映射",
  graphEdgeCategory: "类别",
  graphEdgeFrom: "来源",
  graphEdgeTo: "目标",
  graphEdgeLabel: "标签",
  assetOrigin: "来源",
  assetBanner: "横幅",
  unknownEdge: "未知关系",
  thinking: "思考中...",
  thought: "思考",
  empty: "(空)",
  subagents: "子代理",
  subagent: "子代理",
  subagentOutputUnavailable: "子代理输出不再可用",
  noSubagentOutput: "暂无子代理输出",
  progress: "进度",
  errorPreview: "错误预览",
  resultPreview: "结果预览",
  tools: "工具",
  arguments: "参数",
  output: "输出",
  open: "打开",
  completed: "已完成",
  canceled: "已取消",
  projectInfo: "项目信息",
  atMostImagesAllowed: (max: number) => `最多允许 ${max} 张图片`,
  imageExceedsSize: (name: string) => `${name} 超过 3.75 MB，已跳过`,
  totalImageExceedsSize: "图片总大小超过 6 MB，部分已跳过",
  failedToReadFile: (name: string) => `读取 ${name} 失败`,
  removeImageLabel: "移除图片",
  attachImage: "附加图片",
  interruptStreaming: "中断接收",
  sendMessage: "发送消息",
  cancelAllSubagentTasks: "取消所有运行中的子代理任务",
  noRunningSubagentTasks: "无运行中的子代理任务",
  speakingTo: (name: string) => `正在与 ${name} 对话`,
  clickToSwitchAgent: "点击切换智能体",
  collapse: "收起",
  expand: "展开",
  openWorkspace: "打开工作区",
  sessionsLabel: "会话",
  noOwners: "无所有者",
  ownersWithCount: (count: number) => `所有者: ${count}`,
  findingStatus: "状态",
  findingDecisions: "决策",
  findingBlockers: "阻碍",
  findingNextSteps: "下一步",
  findingNotes: "备注",
  zoomIn: "放大",
  zoomOut: "缩小",
  resetView: "重置视图",
  nodes: "节点",
  edges: "边",
  secret: "密钥",
  networkRequestFailed: "网络请求失败",
  itemsUploaded: (count: number) => `${count} 项已上传`,
  copy: "复制",
  directoryEmpty: "目录为空",
  text: "文本",
  binary: "二进制",
  failedToRenderImage: "渲染图片失败",
  noAgentsAvailable: "暂无可用智能体",
  startNewConversation: "开始新对话",
  askAgentAnything: "向安全运营智能体提问任何问题...",
  switchAgentSubagentWarning: "切换智能体将结束当前子智能体任务",
  closeImagePreview: "关闭图片预览",
  imagePreview: "图片预览",
  openTerminal: "打开终端",
  openScreen: "打开远程桌面",
  browseFiles: "浏览文件",
  openSubagentPanel: "打开子智能体面板",
  previewTruncated: "预览已截断",
  scrollToLatest: "滚动到最新",
  generateReport: "生成报告",
  reportGenerating: "正在生成报告...",
} as const;
